export type Entry = {
  keys: string[];
  title: string;
  pros: string[];
  cons: string[];
};

function entry(keys: string[], title: string, pros: string[], cons: string[]): Entry {
  return { keys, title, pros, cons };
}

export const RAW_ENTRIES: Entry[] = [
  entry(["01", "10"], "The Isolated Ego",
    ["Entirely self-earned wealth, with zero dependency on family financial backing.",
     "A close relative or contact holds a high-profile government position."],
    ["High risk of early baldness and bone density loss.",
     "Sudden, unpredictable blood pressure spikes."]),
  entry(["02", "20"], "The Fluid Mind",
    ["Capable of attracting sudden, massive cash inflows."],
    ["Chronic fluid retention, severe urine infections and kidney issues.",
     "Extreme mood swings.",
     "Money drains away almost as fast as it arrives, through emotional, reckless spending."]),
  entry(["03", "30"], "The Knowledge Barrier",
    ["Accumulates vast, deep knowledge over a lifetime.",
     "Will acquire massive land or property later in life."],
    ["Struggles heavily to present or communicate that knowledge.",
     "Prone to liver enlargement and digestive tract failure.",
     "Intense legal disputes with siblings over the acquired property."]),
  entry(["04", "40"], "The Shockwave",
    ["Sudden, overnight financial windfalls."],
    ["Windfalls are almost immediately followed by legal notices or court cases.",
     "High risk of upper-body accidents and respiratory/breathing issues."]),
  entry(["05", "50"], "The Calculated Trader",
    ["A sharp, business-minded intellect that naturally thinks in lakhs and crores.",
     "Easily accumulates liquid cash through trade, business and calculated speculation."],
    ["Prone to chronic skin allergies and rashes.",
     "Nervous system weakness."]),
  entry(["06", "60"], "The Luxury Burnout",
    ["Wealth flows heavily, especially through connections with the opposite sex."],
    ["Obsessive attachment to branded luxury, expensive cars and show-off spending.",
     "High risk of diabetes, reproductive tract issues and low sperm count.",
     "Wealth is dependent on external relationships rather than self-sufficiency."]),
  entry(["07", "70"], "The Isolated Soul",
    ["Material wealth does eventually unlock, once a decisive life change is made."],
    ["Deep internal anxiety, overthinking and chronic insomnia.",
     "Severe joint pain, arthritis and foot injuries.",
     "Wealth stays blocked until the person cuts off from the father or leaves the birthplace."]),
  entry(["08", "80"], "The Iron Delay",
    ["Wealth does eventually arrive, through hard manual labor or long-term real estate holding."],
    ["Total stagnation and heavy delays in everyday tasks.",
     "Severe iron deficiencies, dental decay and spinal column issues.",
     "Progress toward any goal is incredibly slow."]),
  entry(["09", "90"], "The Aggressive Spark",
    ["High raw energy and drive."],
    ["Explosive anger, with dark red skin flushing when angry.",
     "Blood-related disorders (piles, impurities).",
     "Prone to fire burns and surgical scars; intense litigation over physical property."]),

  entry(["11"], "Ego & Fast Speech",
    ["Naturally quick, sharp speaking ability."],
    ["Speaking speed is abnormally fast, often to a fault.",
     "Frequent migraines and chronic headaches.",
     "Refuses to take advice from anyone, which destroys partnerships."]),
  entry(["12", "21"], "Attractive Face, Cash Leak",
    ["Highly symmetrical, attractive facial structure."],
    ["Money is wasted instantly on fleeting pleasures.",
     "Zero long-term savings capacity."]),
  entry(["13", "31"], "The Corporate Specialist",
    ["Excellent education and high respect within one's circle.",
     "The 31 side specifically pushes toward a high-paying professional career, advisory role or consultancy."],
    []),
  entry(["14", "41"], "The Debt Trap",
    [],
    ["Extreme attraction to taking on massive loan liabilities.",
     "Receives official legal notices.",
     "Suffers hard, unrewarding manual labor with minimal financial return."]),
  entry(["15", "51"], "Father's Fame",
    ["The native's own actions or career path make their father highly famous for a good cause.",
     "Solid command over administrative and management work."],
    []),
  entry(["16", "61"], "Marital Financial Decay",
    [],
    ["Severe spouse health issues.",
     "Highly unstable marital life.",
     "Income drops sharply the moment this number is bought or used."]),
  entry(["17", "71"], "Government Connection",
    ["Money flow never fully stops.",
     "A close relative works a secure government job; strong chance of an MNC role with Work-From-Home benefits."],
    ["Prone to a second marriage if other supporting grid numbers are missing."]),
  entry(["18", "81"], "Father-Son War",
    [],
    ["Severe psychological misunderstandings between father and son.",
     "Heavy government penalties, tax audits or legal fines.",
     "Frequent, unplanned, chaotic job changes."]),
  entry(["19", "91"], "The High Place",
    ["Highly professional, independent and an absolute freedom lover.",
     "Known locally as a 'Rasukhdar' — a highly influential person.",
     "Owns exactly what they set out to acquire."],
    ["Ego tends to destroy partnerships."]),

  entry(["22"], "Depression & BP",
    [],
    ["Severe emotional low phases and clinical depression.",
     "Massive blood pressure fluctuations.",
     "Constant chest and lung congestion."]),
  entry(["23", "32"], "The Hidden Shield",
    ["Faces an unusually high number of enemies and jealous rivals — but none ever gain the power to physically or financially harm them."],
    []),
  entry(["24", "42"], "The Overactive Brain",
    ["Constantly generates and processes plans."],
    ["24/7 mental activity leads to chronic over-exhaustion.",
     "High tendency toward negative or dark thinking patterns.",
     "Requires extreme patience to achieve any result."]),
  entry(["25", "52"], "The Occult Healer",
    ["Hands possess natural healing ('Shafa') power.",
     "Highly successful in occult sciences, astrology or medicine; success often comes through air travel."],
    ["Must strictly avoid financial or stock-broking roles."]),
  entry(["26", "62"], "The Educational Barrier",
    ["Intense attraction toward quick money."],
    ["Major breaks in school or college education.",
     "Severe friction with the mother-in-law after marriage.",
     "Risk of diabetes and low sperm count."]),
  entry(["27", "72"], "The Toxic Liquid",
    ["Excellent, sharp gut intuition."],
    ["Severe joint pain and arthritis (Vaat issues).",
     "Recurrent urinary tract infections or urine-related disease."]),
  entry(["28", "82"], "The Hospital Vault",
    ["Accumulates a decent amount of money."],
    ["Money gets thoroughly drained by excessive medical or hospital bills.",
     "High presence of 'Vish Yog'; history of two marriages within the immediate family tree."]),
  entry(["29", "92"], "The Parasite Wealth",
    ["Possesses a decent amount of money, sustained comfortably."],
    ["That comfort comes from draining or relying on someone else's money.",
     "In a Date of Birth, causes severe relationship breakdowns through extreme egoism."]),

  entry(["33"], "The Blocked Scholar",
    ["High hunger for knowledge."],
    ["That knowledge stays ungrounded and impractical.",
     "Massive expenditure on religious ceremonies, courses or higher education with zero practical financial return."]),
  entry(["34", "43"], "The Shivering Nerve",
    [],
    ["Body prone to sudden shivering fits.",
     "High risk of paralysis or breathing/respiratory failure to someone in the immediate family.",
     "If the digit 8 repeats 3+ times elsewhere in the number, this combination should be avoided entirely."]),
  entry(["35", "53"], "The Home Exile",
    ["Success is fully achievable — once the native relocates."],
    ["Success only comes after moving completely away from the hometown or parental home.",
     "High fear of the father.",
     "Suffers from liquid money blocks."]),
  entry(["36", "63"], "The Presentation Struggle",
    ["Highly principled, with deep, genuine knowledge."],
    ["Struggles miserably to present that knowledge to the world.",
     "Major barriers and delays in completing formal studies."]),
  entry(["37", "73"], "The Complete Identity",
    ["Highly magnetic, complete personality.",
     "Knows exactly how to extract benefits and life-changing wealth from acquired knowledge."],
    []),
  entry(["38", "83"], "The Mediator",
    ["Highly successful as a real estate broker, professional counselor, peacemaker or mediator between warring parties."],
    []),
  entry(["39", "93"], "The Show-Off",
    ["Strong flair for public presentation and image."],
    ["Obsessed with vanity, showing off wealth and superficial luxury.",
     "Heavy duality in nature — one face for the public, another at home."]),

  entry(["44"], "Struggle & Neurological Pain",
    [],
    ["Non-stop, brutal delays in daily routine tasks.",
     "Chronic headaches and memory fog.",
     "High risk of financial fraud carried out by close friends."]),
  entry(["45", "54"], "The Courtroom Regular",
    [],
    ["Recurring hospital visits for unrelated medical reasons.",
     "Recurring, separate courtroom or legal issues throughout life.",
     "Life operates under heavy external restrictions."]),
  entry(["46", "64"], "The Hidden Liaison",
    [],
    ["High probability of extra-marital relationships.",
     "Inter-caste marriage disputes.",
     "Chronic, painful urinary tract infections."]),
  entry(["47", "74"], "The Rahu-Ketu Core",
    ["Honest, highly brilliant mind that places massive importance on personal integrity.",
     "Capable of dramatic, overnight success spikes."],
    ["A pure Rahu-Ketu combination — success is highly volatile, with overnight rises and equally fast falls."]),
  entry(["48", "84"], "The Impure Blood",
    [],
    ["Highly malefic combination.",
     "Blood-related chronic diseases and incurable physical problems.",
     "Extreme deficiency in sexual or marital pleasure."]),
  entry(["49", "94"], "The Dangerous Uniform",
    ["Strong natural fit for uniformed service — military, police or security forces."],
    ["Highly attracted to risky, volatile work.",
     "If negatively aspected, can breed a criminal mindset."]),

  entry(["55"], "The Lazy Communicator",
    ["The moment this person breaks their silence and communicates, money flow increases instantly."],
    ["Extreme physical lethargy and procrastination.",
     "High fat retention around the lower abdomen."]),
  entry(["56", "65"], "The Proud Debtor",
    ["Strong business mind.",
     "Home is always located close to a major landmark (temple, superstore, etc.)."],
    ["Feels immense shame or hesitation asking for their own hard-earned money back."]),
  entry(["57", "75"], "The Public Speaker",
    ["Natural born speaker, writer and PR expert.",
     "Highly expressive — people naturally seek this person out for advice."],
    []),
  entry(["58", "85"], "The Frozen Ledger",
    ["Highly calculated, mathematical mind that talks in lakhs and crores.",
     "Strong fit for a career in money, banking or corporate finance."],
    ["Money tends to get permanently stuck in bad investments."]),
  entry(["59", "95"], "The Tongue Destroyer",
    ["Strong fit for science or commerce careers."],
    ["Destroys their finest relationships through bad, harsh or abusive speech.",
     "Arts-field careers are likely to fail this person."]),

  entry(["66"], "The Luxury Trap",
    [],
    ["Heavy spending on vanity, cosmetic enhancements and show-off items — even while in deep debt.",
     "Prone to sudden vision drop or recurrent eye infections."]),
  entry(["67", "76"], "The Broken Canopy",
    [],
    ["High chance a love marriage ends in bitter disaster.",
     "Severe spouse health problems.",
     "Disrupted, sexless or detached married life."]),
  entry(["68", "86"], "The Eye Affliction",
    [],
    ["Specific eye diseases or systemic issues in one particular organ.",
     "If digit 1 repeats multiple times in the DOB, this combination should never be recommended."]),
  entry(["69", "96"], "The Opposite Magnet",
    ["Masterful management skills; excellent corporate planner."],
    ["Faces non-stop, messy involvements or complications with the opposite sex that stall career progress."]),

  entry(["77"], "Overthinking & Sleep Loss",
    [],
    ["Non-stop mental loop chatter.",
     "Heavy clinical anxiety and severe insomnia.",
     "Skin peeling from the palms of the hands or soles of the feet."]),
  entry(["78", "87"], "The Self-Made Healer",
    ["High idealistic values.",
     "Possesses the raw inner power to solve any crisis or financial bankruptcy through sheer willpower."],
    []),
  entry(["79", "97"], "The Paternal Break",
    ["Material and career success does eventually trigger."],
    ["Success only comes after a complete, bitter separation or emotional distance from the biological father."]),

  entry(["88"], "The Obstacle Course",
    [],
    ["Complete, frustrating stagnation in career growth.",
     "Chronic knee cap pain, joint cracking or early arthritis.",
     "Money gets locked up in litigation or bad, unrecoverable debts."]),
  entry(["89", "98"], "The Argumentative Wall",
    ["Works purely on rigid, unwavering principles."],
    ["Highly argumentative nature.",
     "Develops a painful chronic health issue later in life."]),

  entry(["99"], "Blood, Anger & Debt",
    [],
    ["Heavy, compounding loan liabilities.",
     "Explosive, violent anger tantrums; dark red skin tone when angry.",
     "High risk of blood disorders and piles."]),
];

export const PAIR_MAP: Record<string, Entry> = {};
RAW_ENTRIES.forEach((e) => e.keys.forEach((k) => { PAIR_MAP[k] = e; }));

export const TRIPLE_MAP: Record<string, { title: string; pros: string[]; cons: string[] }> = {
  "1": { title: "The Absolute Dictator", pros: ["Powerful, dominant, self-directed drive when running an independent venture."], cons: ["Severe heart palpitations.", "Extreme baldness by early youth.", "Total psychological detachment from the father.", "Cannot work under an employer — leads to immediate firing or complete business bankruptcy."] },
  "2": { title: "The Suicidal Mindset", pros: [], cons: ["Severe psychiatric issues.", "Extreme phobia of deep water bodies.", "Chronic lung/fluid infections.", "Continuous financial drainage through heavy medical bills for the mother's health."] },
  "3": { title: "The Arrogant Guru", pros: ["Deep, extensive personal knowledge base."], cons: ["Severe liver enlargement and uncontrollable cholesterol spikes.", "Complete breakdown of formal academic education.", "Treats others as uneducated or inferior, destroying professional networks."] },
  "4": { title: "The Jail & Accident Combo", pros: [], cons: ["Multiple hostile encounters with law enforcement.", "Structural or building accidents.", "Phantom body pains that medical science cannot diagnose.", "Sudden, overnight bankruptcy."] },
  "5": { title: "The Stagnant Trader", pros: [], cons: ["Total loss of speech clarity; heavy stammering under pressure.", "Full nervous breakdowns.", "Wealth freezes solid — businesses face sudden government lockouts or sealing."] },
  "6": { title: "The Public Scandal", pros: [], cons: ["Severe urinary tract destruction.", "Loss of reproductive/seminal health.", "Massive public humiliation from extra-marital, hidden or illegal relationships."] },
  "7": { title: "The Extreme Hermit", pros: [], cons: ["Total social isolation and deep depression.", "Severe spinal column injuries.", "Massive betrayal by religious gurus or trusted figures.", "Complete loss of material assets — a nomadic life."] },
  "8": { title: "The Physical Paralysis", pros: [], cons: ["High risk of paralysis or long-term physical immobility.", "Lifetime dependence on heavy psychiatric or physical medication.", "Asset freezing by courts or national banks."] },
  "9": { title: "The Blood & Fire Combo", pros: [], cons: ["High probability of major surgical operations.", "Severe bloodshed through road accidents.", "Properties catching fire.", "Uncontrollable criminal rage leading to imprisonment."] },
};

export type GatewayRow = {
  decade: number;
  best: number[];
  bestDesc: string;
  neutral: number[];
  neutralDesc: string;
  bad: number[];
  badDesc: string;
};

export const GATEWAY: GatewayRow[] = [
  { decade: 1, best: [13, 15, 19], bestDesc: "Corporate growth, father's fame, and high public authority.", neutral: [12, 17], neutralDesc: "Attractive face appearance, minor cash leakage, and stable government links.", bad: [11, 14, 16, 18], badDesc: "Recurrent migraines, heavy loan debt, early marital failure, and severe tax fines." },
  { decade: 2, best: [23, 25], bestDesc: "Destroys all enemies; extreme success in occult, astrology, and medical fields.", neutral: [27, 29], neutralDesc: "Sharp gut intuition but dependent on draining external wealth.", bad: [22, 24, 26, 28], badDesc: "Clinical depression, dark destructive thoughts, and extreme hospital bills." },
  { decade: 3, best: [31, 37, 38], bestDesc: "High-paying consultancy work and massive real estate or brokering profits.", neutral: [32, 39], neutralDesc: "Protected from rivals but a high tendency for double-faced vanity.", bad: [33, 34, 35, 36], badDesc: "Blocked knowledge, sudden paralysis risk, home exile, and extreme speech blocks." },
  { decade: 4, best: [47], bestDesc: "Highly brilliant mind with massive, volatile overnight success spikes.", neutral: [42, 49], neutralDesc: "Overactive brain processing; strong fit for high-risk uniform or military jobs.", bad: [41, 43, 44, 45, 46, 48], badDesc: "Court trials, hospital loops, systemic infections, and major fraud loss." },
  { decade: 5, best: [51, 56, 57], bestDesc: "Administrative control, business fortune, and highly expressive public speaking.", neutral: [52, 53, 55], neutralDesc: "Air travel luck, success triggers far from home, and lazy but active cash flow.", bad: [54, 58, 59], badDesc: "Courtroom loops, permanently frozen ledger investments, and abusive, toxic speech." },
  { decade: 6, best: [68, 69], bestDesc: "Strategic corporate management mastery and high wealth through the opposite sex.", neutral: [60, 62], neutralDesc: "Heavy luxury spending loops and sudden breaks in formal education.", bad: [61, 63, 64, 65, 66, 67], badDesc: "Marital bankruptcy, public scandals, early eye failures, and deep debt traps." },
  { decade: 7, best: [71, 73, 78], bestDesc: "MNC/WFH corporate salary, complete identity, and self-made financial revival.", neutral: [72, 74, 75], neutralDesc: "High gut instincts, volatile Rahu-Ketu spikes, and a crowd coming for advice.", bad: [76, 77, 79], badDesc: "Broken marriage canopy, severe chronic insomnia, and total father alienation." },
  { decade: 8, best: [83, 87], bestDesc: "High mediator commissions and massive raw willpower to survive bankruptcy.", neutral: [85, 88], neutralDesc: "Calculated mathematical mind but stuck with constant career stagnation.", bad: [81, 82, 84, 86, 89], badDesc: "Father-son war, chronic joint pain, blood decay, and physical paralysis." },
  { decade: 9, best: [91, 96], bestDesc: "Highly influential status, 'Rasukhdar' persona, and corporate executive wealth.", neutral: [92, 93, 95, 97], neutralDesc: "Parasite money, extreme vanity, harsh speech, and a strict focus on science streams.", bad: [94, 98, 99], badDesc: "Criminal mindset tendencies, chronic later-life illnesses, and heavy, crushing loan liabilities." },
];

export type GatewayTier = "best" | "neutral" | "bad";
export function gatewayLookup(n: number): { tier: GatewayTier; desc: string } | null {
  const dec = Math.floor(n / 10);
  const row = GATEWAY.find((r) => r.decade === dec);
  if (!row) return null;
  if (row.best.includes(n)) return { tier: "best", desc: row.bestDesc };
  if (row.neutral.includes(n)) return { tier: "neutral", desc: row.neutralDesc };
  if (row.bad.includes(n)) return { tier: "bad", desc: row.badDesc };
  return null;
}

export const ROOT: Record<number, { planet: string; persona: string; lucky: number[]; neutral: number[]; bad: number[]; badDesc: string }> = {
  1: { planet: "Sun", persona: "The King", lucky: [1, 5, 6], neutral: [2, 3, 7, 9], bad: [8, 4], badDesc: "Causes extreme career delays, litigation, and massive ego blocks." },
  2: { planet: "Moon", persona: "The Queen", lucky: [1, 3, 5], neutral: [2, 7], bad: [4, 8, 9, 6], badDesc: "Causes severe depression, heavy liquid cash drainage, and toxic relationships." },
  3: { planet: "Jupiter", persona: "The Guru", lucky: [1, 3, 5, 7], neutral: [2, 9], bad: [6, 4, 8], badDesc: "Destroys presentation skills, blocks wealth, and creates massive family disputes." },
  4: { planet: "Rahu", persona: "The Rebel", lucky: [1, 5, 6], neutral: [7, 8], bad: [9, 2, 4], badDesc: "Triggers sudden courtroom cases, physical accidents, and overnight bankruptcy." },
  5: { planet: "Mercury", persona: "The Prince", lucky: [1, 5, 6], neutral: [2, 3, 7, 8, 9], bad: [4], badDesc: "Freezes communication, brings sudden nervous breakdowns, and stops money flow." },
  6: { planet: "Venus", persona: "The Luxury", lucky: [1, 5, 6, 7], neutral: [2, 9], bad: [3, 4, 8], badDesc: "Triggers severe health issues for the spouse, public scandals, and immense debt." },
  7: { planet: "Ketu", persona: "The Mystic", lucky: [1, 3, 5, 6], neutral: [2, 4, 7, 8], bad: [9], badDesc: "Triggers absolute emotional isolation, severe joint pain, and betrayal by close associates." },
  8: { planet: "Saturn", persona: "The Judge", lucky: [3, 5, 6], neutral: [4, 7, 8], bad: [1, 2, 9], badDesc: "Triggers extreme accidents, structural delays, and non-stop clashes with authorities." },
  9: { planet: "Mars", persona: "The Commander", lucky: [1, 3, 5], neutral: [2, 7, 9], bad: [4, 8, 6], badDesc: "Triggers explosive criminal rage and severe bloodshed/surgeries." },
};
